startupProject/src/main/java/com/startup/startupProject/Controller/TestController.java

React와의 통신 테스트를 위한 TestController 생성
경로는 /test로 임시 지정

React와 통신 테스트를 위한 TestController

---

startupProject/src/main/front_end/package-lock.json
startupProject/src/main/front_end/package.json
startupProject/src/main/front_end/src/App.js
startupProject/src/main/front_end/src/setProxy.js

React와 Spring 사이의 데이터 주고받기 및 연동

---

startupProject/build.gradle
startupProject/src/main/front_end/package.json

proxy설정 추가했고, gson의존성 추가 했습니다. 확인 부탁드립니다.

프록시 설정 및 gson의존성 추가

---

startupProject/build.gradle

build.gradle에 Spring build 진행시 동시에 react도 build 되도록 수정

---

startupProject/src/main/front_end/src/component/secondPage/FuncApp.css
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.css
startupProject/src/main/front_end/src/component/secondPage/Recorder.css
startupProject/src/main/front_end/src/component/secondPage/Recorder.tsx

Fix Recorder, FuncApp, FuncList component

---

startupProject/src/main/front_end/src/component/secondPage/Recorder.tsx

Recorder.tsx 파일에서 webm포맷으로 음성 녹음을 실시하고
wav포맷으로 인코딩하여 서버측으로 보내는 방식으로 수정했습니다.
차후 raw 데이터 변환이 수월하기 위해 실시했습니다.

Fix Recorder component

---

startupProject/src/main/java/com/startup/startupProject/Service/ETRIapiService.java
startupProject/src/main/java/com/startup/startupProject/Service/WavToRaw.java
startupProject/src/main/java/com/startup/startupProject/upload/domain/Controller/UploadFileController.java
startupProject/src/main/java/com/startup/startupProject/upload/domain/dto/FileUploadResponse.java

ETRIService에서 RestApi통신을 통해 점수를 받아온 후에 Raw파일을 자동으로 삭제하도록 기능을 추가하였습니다.
또한 Getter, Setter, Constructor를 lombok 라이브러리릍 통해  어노테이션으로 수정하였습니다.

Create ETRIService & Delete Raw file

---

startupProject/src/main/front_end/src/component/secondPage/DataView.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.css
startupProject/src/main/front_end/src/component/secondPage/FuncList.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.css
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx
startupProject/src/main/front_end/src/index.css
startupProject/src/main/front_end/src/index.tsx

FuncApp의 하위 컴포넌트 개발 및 스타일 추가
테스트 스크립트에 카드 형식의 스타일을 추가했습니다.
원형 이벤트 혹은 드래그 스크롤 이벤트를 적용할 계획입니다.
SubDataList 컴포넌트에 text는 테스트를 위한 임의의 스크립트 객체배열입니다.

Develop FuncApp Page

---

startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

에러를 유발하는 SubDataList 컴포넌트의 import구문을 삭제했습니다.

Delete Import Line

---

startupProject/src/main/front_end/src/component/Header.css
startupProject/src/main/front_end/src/component/firstPage/BgElement.css
startupProject/src/main/front_end/src/component/firstPage/BgElement.tsx
startupProject/src/main/front_end/src/component/firstPage/Summary.css
startupProject/src/main/front_end/src/component/firstPage/Summary.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.css
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.css
startupProject/src/main/front_end/src/component/secondPage/SubDataList.css
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1. UI요소를 침범하지 않도록 Logo 크기를 수정했습니다.
2. 메인화면의 배경을 모듈화하여 재사용 할 수 있도록 했습니다.
3. 2번째 페이지의 배경를 추가했습니다.
4. 2번째 페이지의 계층관계를 수정했습니다. 
5. 이제 SubDataList 컴포넌트는 스크롤을 이용하여 접근할 수 있습니다.

Font-End : Current work situation

---

startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.css
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

Func페이지에서 List 화면에 노출될 때만 "Use the mouse wheel!" 텍스트가 등장하도록 변경했습니다.

Fix message

---

startupProject/src/main/front_end/src/App.tsx
startupProject/src/main/front_end/src/component/firstPage/Category.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1.  터미널 상의 warning문구를 숨깁니다.
2. 첫번째 페이지에서 접근된 객체의 state 값을 두번째 페이지로 전달합니다.
3.  두번째 페이지에서 useLocation Hook을 이용하여 state값을 받습니다.
+ useEffect의 무한루프를 해결했습니다.
+ 몇몇 디자인과 이벤트를 수정하였습니다.

Passing state between pages

---

startupProject/build.gradle
startupProject/src/main/java/com/startup/startupProject/data/Controller/DataController.java

1. func URL 매핑 시 임시 데이터에서 추출한 값을 JSONArray형태로 전달
2. build.grade에 lombok의존성 추가로 주입

URL mapping & temporary data transfer

---

startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx

테스트 할 수 있도록 FuncApp 컴포넌트에 코드를 추가했습니다.

Add Data Receiver

---

startupProject/src/main/front_end/src/App.tsx

Delete test code

---

startupProject/src/main/java/com/startup/startupProject/data/Controller/DataController.java
startupProject/src/main/java/com/startup/startupProject/data/service/ScriptService.java

일부 Service에서 수정이 필요한 annotation을 수정했으며, Test 데이터 전송 시 JsonArray에서 String 으로 변환했습니다.
`return jsonArray.toString();`

Modify data transfer variables

---

startupProject/src/main/java/com/startup/startupProject/Errorpage/Controller/ErrorPageController.java
startupProject/src/main/java/com/startup/startupProject/data/Controller/DataController.java

1. DataController부분에 생성자를 
`@RequiredArgsConstructor` annotation으로 대체했습니다.
2. ErrorPage Mapping 을 위한 URL 부분에
`@GetMapping({"/", "/error", "/func"})`으로 변경하였습니다.
3. Rest Api 통신을 위한 url 주소를 
`@GetMapping("/api/articles")` 로 수정하였습니다.
확인 해주시고 피드백 부탁드립니다.

Added some annotations and modified Rest API paths

---

startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx

백앤드와 프론트앤드가 사용하는 경로를 분리하는 작업을 수행했습니다.

Fix Mapping URL

---

startupProject/src/main/front_end/src/App.tsx
startupProject/src/main/front_end/src/component/firstPage/Category.tsx
startupProject/src/main/front_end/src/component/secondPage/DataView.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx

1. 테스트를 위한 console.log 코드들을 삭제했습니다.
2. FuncApp에서 Mapping을 위한 useEffect의 무한루프 오류를 해결했습니다.
3. App.tsx의 사용하지 않는 state 변수를 삭제했습니다.

Current Work State

---

startupProject/src/main/front_end/src/component/firstPage/Category.css
startupProject/src/main/front_end/src/component/secondPage/DataView.css
startupProject/src/main/front_end/src/component/secondPage/DataView.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.css
startupProject/src/main/front_end/src/component/secondPage/FuncList.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1. DataView 컴포넌트위 가시성 속성에 이벤트를 추가했습니다. (modal type)
2. 전달받은 DB 데이터를 시스템에 맞게 parsing했습니다. 
3. 필요에 의해 몇몇 컴포넌트에 드래그 방지 코드와 요소 hover시 pointer 커서를 추가했습니다.
ps) 임시로 실제 데이터를 프론트앤드에서 샘플링하여 작업진행했습니다. 이후 프론트에서 백으로 tartget값을 요청하는 로직이 완성되면 삭제 후 수정하겠습니다.

Add data processing & Fix DataView component in FuncPage 

---

startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/java/com/startup/startupProject/data/Controller/DataController.java
startupProject/src/main/java/com/startup/startupProject/data/dto/business.java
startupProject/src/main/java/com/startup/startupProject/data/dto/drama.java
startupProject/src/main/java/com/startup/startupProject/data/dto/movie.java
startupProject/src/main/java/com/startup/startupProject/data/mapper/ScriptMapper.java
startupProject/src/main/java/com/startup/startupProject/data/service/ScriptService.java
startupProject/src/main/resources/mapper/ScriptMapper.xml
startupProject/src/test/java/com/startup/startupProject/data/mapper/ScriptMapperTest.java

1. DataBase에서 데이터 교환을 위한 DTO 생성
2. ScriptService를 통해 각 Table별 값을 List로 반환하는 코드 추가
3. React와 연동을 위한 Rest Api 통신 url 수정 및 세분화
4. xml파일에 추가된 데이터 select문 추가
5. 수정된 url을 바탕으로 FuncApp에서 axios로 받는 url 수정

Adding database-related content and refining the Rest API

---

startupProject/src/main/java/com/startup/startupProject/data/dto/daily.java
startupProject/src/main/java/com/startup/startupProject/data/dto/drama.java
startupProject/src/main/resources/mapper/ScriptMapper.xml

전달되는 변수 명 변경 및 DB Column명 변경에 따른 mapper에 Select문 수정했습니다.

Change the data variables passed and modify the mapper

---

startupProject/src/main/resources/mapper/ScriptMapper.xml

Drama Table Column명 변경에 따른 select문 수정했습니다.

DB Column명 변경에 따른 select문 변경

---

startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.css
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1. FuncApp 소스코드 수정
-> 기존 test데이터 제거
-> 서버의 url에 해당 flag(click state value)지정 및 호출
2. SubDataList 소스코드 수정
-> 스크립트 문자열 레이아웃 수정 (p태그 추가)
3. SubDataList 스타일 수정

Processing the data received from the backend

---

startupProject/src/main/java/com/startup/startupProject/upload/domain/Controller/UploadFileController.java

React에서 보낸 Script 값을 받아와 AI API/DATA와 Rest Api 통신을 통해 대사와 raw값을 전달하여 score를 반환하도록 수정했습니다.
현재는 임시로 서버 상에만 받아온 값을 출력하도록 설정되어 있습니다.

Script 데이터를 받아와 녹음 파일과 matching

---

startupProject/src/main/front_end/src/App.tsx
startupProject/src/main/front_end/src/component/secondPage/Animation/OnAir.css
startupProject/src/main/front_end/src/component/secondPage/Animation/OnAir.tsx
startupProject/src/main/front_end/src/component/secondPage/DataView.css
startupProject/src/main/front_end/src/component/secondPage/DataView.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/Recorder.css
startupProject/src/main/front_end/src/component/secondPage/Recorder.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1. 소스코드의 사용하지 않는 코드들을 제거했습니다.
3. DataView의 래이아웃과 디자인을 작업했습니다.
4. Recorder의 기능 부분과 클릭시 상태변화를 작업했습니다.
5. start recording 버튼을 누르면 현재 녹음 중을 알리는 Animation 객체를 추가했습니다. (Animation/OnAir.tsx)

Fix DataView & Add Animation

---

startupProject/src/main/java/com/startup/startupProject/upload/domain/Controller/UploadFileController.java

기존에 있던 FileUploadResponse에서 scoreString 값으로 변수를 반환하도록 수정했습니다.
scoreString 이라는 String값으로 점수가 넘어가는지 확인 해주시면 감사하겠습니다.

Rename return type and variable

---

startupProject/src/main/front_end/src/App.tsx
startupProject/src/main/front_end/src/component/secondPage/DataView.css
startupProject/src/main/front_end/src/component/secondPage/DataView.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.css
startupProject/src/main/front_end/src/component/secondPage/Recorder.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.css
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1. 녹음창의 디자인을 추가했습니다.
2. 점수창 추가 및 디자인.
3. 카드 디자인 및 호버액션 추가
4. 서버에서 점수 받아오는 URL 추가

Add Design & Fix component

---

startupProject/src/main/front_end/src/App.tsx
startupProject/src/main/front_end/src/component/secondPage/Recorder.tsx
startupProject/src/main/front_end/src/component/secondPage/ScoreView.tsx

1. ScoreView의 데이터 송수신 코드를 Recorder로 옮겼습니다.
2. 사용하지 않는 소스코드를 삭제했습니다.

Add response logic

---

startupProject/src/main/front_end/src/component/secondPage/Animation/PartLoading.css
startupProject/src/main/front_end/src/component/secondPage/Animation/PartLoading.tsx
startupProject/src/main/front_end/src/component/secondPage/Recorder.tsx
startupProject/src/main/front_end/src/component/secondPage/ScoreView.css
startupProject/src/main/front_end/src/component/secondPage/ScoreView.tsx
startupProject/src/main/front_end/src/component/secondPage/SubDataList.tsx

1. 서버 통신이 포함된 실행부에 로딩을 구현했습니다. (PartLoading.tsx)
2. score 범위에 0이 포함되어 초기값을 구분하기위해 -1로 재설정 했습니다.
3. 기존 ScoreView에서 점수 중복 현상을 방지하기 위해서 버튼을 Go back으로 변경하여 클릭 이벤트가 발생했을 때 SubDataView로 이동하도록 변경 했습니다.
4. score의 값에 따라 ScoreView에 노출되는 요소들에 차별화를 주었습니다.
5. 디자인을 소폭 수정했습니다.

Add Loading & Perform differentiated rendering by score

---

startupProject/src/main/java/com/startup/startupProject/Service/ETRIapiScriptService.java
startupProject/src/main/java/com/startup/startupProject/Service/ETRIapiService.java
startupProject/src/main/java/com/startup/startupProject/upload/domain/Controller/UploadFileController.java

AI/API Data에 음성인식 기능을 통해 STT기능을 위한 Service를 추가했습니다.
Controller부분에서 추가로 점수값과 같이 발음한 스크립트도 넘겨주도록 수정했습니다.
추가로 일부 console에 찍히는 값들 또한 수정해서 올려뒀습니다.

Add code for the Speech to text feature

---

startupProject/src/main/front_end/src/component/secondPage/ScoreView.css
startupProject/src/main/front_end/src/component/secondPage/ScoreView.tsx

ScoreView의 레이아웃을 대폭 변경했습니다.
- 점수를 나타내는 섹션과 STT를 나타낼 섹션을 분리했습니다.

Fix layout of Scoreview comp

---

startupProject/src/main/front_end/src/component/Header.tsx
startupProject/src/main/front_end/src/component/secondPage/DataView.css
startupProject/src/main/front_end/src/component/secondPage/DataView.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/front_end/src/component/secondPage/FuncList.tsx
startupProject/src/main/front_end/src/component/secondPage/Recorder.css
startupProject/src/main/front_end/src/component/secondPage/ScoreView.tsx
startupProject/src/main/front_end/src/component/secondPage/TTSView.css
startupProject/src/main/front_end/src/component/secondPage/TTSView.tsx

1. 상태 변경이 발생하는 state에 memo를 적용하여 불필요한 렌더링이 발생하지 않도록 수정했습니다.
2. log 출력 코드를 삭제했습니다.

React.memo를 적용 및 log 출력 코드 삭제

---

startupProject/src/main/java/com/startup/startupProject/data/Controller/DataController.java

Controller부분 일부 어노테이션 수정

---

startupProject/build.gradle
startupProject/src/main/front_end/src/component/secondPage/FuncApp.tsx
startupProject/src/main/java/com/startup/startupProject/Service/WavToRaw.java
startupProject/src/main/java/com/startup/startupProject/data/Controller/DataController.java
startupProject/src/main/java/com/startup/startupProject/upload/domain/Controller/UploadFileController.java
startupProject/src/main/resources/application.properties

1. NotNull어노테이션이 계속 오류 발생으로 인해 org.jetbrains:annotations:16.0.2 추가했습니다.
2. 일부 콘솔창에 출력되는 JSON값과 결과 값을 주석처리 및 삭제했습니다.
3. build.gradle에 mySQL관련 dependency를 추가했습니다.
4. DB를 Oracle DB -> MySQL로 변경 및 aws rds와 연동시켰습니다.
5. axios api 통신 부분을 수정하였습니다.
확인 부탁드리겠습니다.

dependencies 추가, DB 변경, API통신 url 변경

---

startupProject/src/main/java/com/startup/startupProject/Service/ETRIapiScriptService.java

주석 및 실패 문구 추가

---

startupProject/build.gradle

CI/CD 배포시 npm 에러를 수정하기 위한 코드 추가했습니다.

npm 배포 에러 수정
